// Browser check for multi-season selection and the All-time tab. Run with the server on 8050.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1440,height:1000}});const errs=[];p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>m.type()==='error'&&errs.push(m.text()));
const api=await (await p.request.get('http://localhost:8050/api/data')).json();
await p.goto('http://localhost:8050/#overview');await p.waitForSelector('#content:not([hidden])');
assert.equal(await p.textContent('#season-button'),'2026');
await p.click('#season-button');
await p.check('[data-season-value="2025"]');await p.check('[data-season-value="2023"]');
await p.click('[data-season-close]');
const pick=new Set(['2026','2025','2023']);
const pga=r=>r.org_id==='1';const rows=api.players.filter(r=>pga(r)&&pick.has(r.season_year)), teams=api.teams.filter(r=>pga(r)&&pick.has(r.season_year));
const players=new Set(rows.map(r=>r.player_id)).size;
const events=new Set([...rows,...teams].map(r=>r.season_year+r.tournament_id)).size;
assert.equal(await p.locator('.metric-value').nth(0).textContent(), events.toLocaleString('en-US'));
assert.equal(await p.locator('.metric-value').nth(1).textContent(), players.toLocaleString('en-US'));
const wins={};rows.filter(r=>r.finish_rank===1).forEach(r=>wins[r.player_id]=(wins[r.player_id]||0)+1);
await p.click('[data-metric="wins"]');
assert.equal(await p.locator('.bar-value').first().textContent(), String(Math.max(...Object.values(wins))));
await p.click('nav [data-view="alltime"]');await p.waitForTimeout(800);
assert.ok(await p.isDisabled('#season-button'));
const allWins={};api.players.filter(r=>pga(r)&&r.finish_rank===1).forEach(r=>allWins[r.player_id]=(allWins[r.player_id]||0)+1);
assert.equal(await p.locator('.bar-value').first().textContent(), String(Math.max(...Object.values(allWins))));
await p.selectOption('#tour','liv');await p.waitForTimeout(300);
const livIds=new Set(api.players.filter(r=>r.org_id==='liv').map(r=>r.player_id));
for(const key of await p.$$eval('[data-season-hint]',b=>b.map(x=>x.dataset.player)))assert.ok(livIds.has(key.split('/')[1]),'Best seasons must stay within the selected tour');
await p.selectOption('#tour','1');
await p.click('[data-career-metric="top10_rate"]');await p.waitForTimeout(300);
await p.locator('.bar-row').first().click();await p.waitForTimeout(600);
await p.click('nav [data-view="tournaments"]');
assert.deepEqual(errs,[]);console.log('PASS: multi-season totals, wins leader, All-time lock and career leader, cross-season navigation.');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
